volumes:
  byob-data:
    external: true

  pg-admin:
    external: true

services:
  byob-service:
    build:
      context: ./byob-service
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./byob-service:/app
    environment:
      DATABASE_URL: postgresql://byob:password@postgres/byob
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: ovPvU5MchtfiVrzSby0qNfYP9uhM

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_BYOB_SERVICE_API_HOST: http://localhost:8000

  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - byob-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=byob
      - POSTGRES_PASSWORD=password
    ports:
      - 15432:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ADMIN@HACKREACTOR.COM
      PGADMIN_DEFAULT_PASSWORD: PASSWORD
      PGADMIN_DISABLE_POSTFIX: 1
